# templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "epm-automate.fullname" . }}-configmap
data:
  epm-login: "{{ .Values.epm.login }}"
  epm-password: "{{ .Values.epm.password }}"
  epm-url: "{{ .Values.epm.url }}"
  epm-task: "{{ .Values.epm.task }}"
